In [1]:
import pandas as pd

url = "https://raw.githubusercontent.com/datasciencedojo/datasets/master/titanic.csv"
df = pd.read_csv(url)

In [2]:
df = pd.read_csv('test_data/pitstop/train.csv')
df.head()

,id,Driver,Compound,Race,Year,PitStop,LapNumber,Stint,TyreLife,Position,LapTime (s),LapTime_Delta,Cumulative_Degradation,RaceProgress,Position_Change,PitNextLap
0,0,D109,HARD,Canadian Grand Prix,2022,0,50,2,39.0,8,78.491,-7.564,21.019,0.714286,5.0,1.0
1,1,D086,HARD,Dutch Grand Prix,2025,1,27,2,7.0,4,75.095,-32.617,-223.207,0.346154,-3.0,0.0
2,2,ZON,HARD,Austrian Grand Prix,2022,0,59,3,22.0,13,70.945,-7.540,-100.529,0.819444,3.0,1.0
3,3,SPE,MEDIUM,Pre-Season Testing,2023,0,2,1,2.0,7,94.361,-7.324,-7.324,0.076923,0.0,0.0
4,4,D019,HARD,Azerbaijan Grand Prix,2022,1,26,3,6.0,2,107.878,8.965,-14.139,0.361111,3.0,0.0

In [7]:
df.describe()

,id,Year,PitStop,LapNumber,Stint,TyreLife,Position,LapTime (s),LapTime_Delta,Cumulative_Degradation,RaceProgress,Position_Change,PitNextLap
count,439140.000000,439140.000000,439140.000000,439140.000000,439140.000000,439140.000000,439140.000000,439140.000000,439140.000000,439140.000000,439140.000000,439140.000000,439140.000000
mean,219569.500000,2023.523544,0.136118,23.105909,1.789113,14.158231,9.630339,90.948735,-3.770040,-25.721759,0.337661,0.101542,0.198982
std,126768.942943,1.024930,0.342915,16.958261,0.950194,9.801338,5.278770,19.772769,43.945759,54.766573,0.253277,4.006765,0.399235
min,0.000000,2022.000000,0.000000,1.000000,1.000000,1.000000,1.000000,67.694000,-2403.895000,-274.564000,0.012821,-18.000000,0.000000
25%,109784.750000,2023.000000,0.000000,9.000000,1.000000,6.000000,5.000000,82.621000,-8.884000,-46.566250,0.129870,-1.000000,0.000000
50%,219569.500000,2024.000000,0.000000,19.000000,2.000000,12.000000,10.000000,90.521000,-0.295000,-20.994000,0.269231,0.000000,0.000000
75%,329354.250000,2024.000000,0.000000,36.000000,2.000000,20.000000,14.000000,98.471000,0.115000,-6.199000,0.513158,2.000000,0.000000
max,439139.000000,2025.000000,1.000000,78.000000,8.000000,77.000000,20.000000,2507.607000,2423.932000,2412.026000,1.000000,18.000000,1.000000

In [3]:
import ydata_profiling
ydata_profiling.ProfileReport(df, minimal=True, progress_bar=False)

/var/folders/_n/_4wq73hd55l5n2c4btbj96640000gn/T/ipykernel_42901/779946972.py:1: DeprecationWarning:
    `import ydata_profiling` is deprecated and will not receive more updates.
    Please install fg-data-profiling via `pip install fg-data-profiling` and use `import data_profiling` instead.

  import ydata_profiling
100%|██████████| 16/16 [00:00<00:00, 46.11it/s]

In [4]:
k = "MDE5ZDY4ODYtZTY1ZC03YWRmLTlkNTMtODYyNzJmYmU1ZDA3OjI3MzQxNmJlLWM0MGMtNDZhOC1hNTcxLTMzOWIwZjFlZjYwYQ=="


# pip install langchain-gigachat

# model.get_models() список доступных моделей
from langchain_gigachat import GigaChat

model = GigaChat(
    model="GigaChat-2-Max",
    credentials=k,
    scope="GIGACHAT_API_CORP",
    verify_ssl_certs=False,
)
model.get_models()
# model.invoke("Hello, how are you?")

Models(x_headers={'x-request-id': 'a81d3092-9590-4657-be16-62582637dcb0', 'x-session-id': '34979a45-2fcc-41c8-a826-2306f041e11c', 'x-client-id': None}, data=[Model(x_headers=None, id_='GigaChat', object_='model', owned_by='salutedevices'), Model(x_headers=None, id_='GigaChat-2', object_='model', owned_by='salutedevices'), Model(x_headers=None, id_='GigaChat-2-Max', object_='model', owned_by='salutedevices'), Model(x_headers=None, id_='GigaChat-2-Max-preview', object_='model', owned_by='salutedevices'), Model(x_headers=None, id_='GigaChat-2-Pro', object_='model', owned_by='salutedevices'), Model(x_headers=None, id_='GigaChat-2-Pro-preview', object_='model', owned_by='salutedevices'), Model(x_headers=None, id_='GigaChat-2-preview', object_='model', owned_by='salutedevices'), Model(x_headers=None, id_='GigaChat-Max', object_='model', owned_by='salutedevices'), Model(x_headers=None, id_='GigaChat-Max-preview', object_='model', owned_by='salutedevices'), Model(x_headers=None, id_='GigaChat-Plus', object_='model', owned_by='salutedevices'), Model(x_headers=None, id_='GigaChat-Pro', object_='model', owned_by='salutedevices'), Model(x_headers=None, id_='GigaChat-Pro-preview', object_='model', owned_by='salutedevices'), Model(x_headers=None, id_='GigaChat-preview', object_='model', owned_by='salutedevices'), Model(x_headers=None, id_='GigaCheckClassification', object_='model', owned_by='salutedevices'), Model(x_headers=None, id_='GigaCheckDetection', object_='model', owned_by='salutedevices'), Model(x_headers=None, id_='Embeddings', object_='model', owned_by='salutedevices'), Model(x_headers=None, id_='Embeddings-2', object_='model', owned_by='salutedevices'), Model(x_headers=None, id_='EmbeddingsGigaR', object_='model', owned_by='salutedevices'), Model(x_headers=None, id_='GigaEmbeddings-3B-2025-09', object_='model', owned_by='salutedevices')], object_='list')